name: mi_card
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/_DSC0210.jpg

  fonts:
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf

    - family: SourceSans3
      fonts:
        - asset: assets/fonts/SourceSans3-Black.ttf
        - asset: assets/fonts/SourceSans3-BlackItalic.ttf
        - asset: assets/fonts/SourceSans3-Bold.ttf
        - asset: assets/fonts/SourceSans3-BlackItalic.ttf
        - asset: assets/fonts/SourceSans3-ExtraBold.ttf
        - asset: assets/fonts/SourceSans3-ExtraBoldItalic.ttf
        - asset: assets/fonts/SourceSans3-ExtraLight.ttf
        - asset: assets/fonts/SourceSans3-ExtraLightItalic.ttf
        - asset: assets/fonts/SourceSans3-Italic.ttf
        - asset: assets/fonts/SourceSans3-Light.ttf
        - asset: assets/fonts/SourceSans3-LightItalic.ttf
        - asset: assets/fonts/SourceSans3-Medium.ttf
        - asset: assets/fonts/SourceSans3-MediumItalic.ttf
        - asset: assets/fonts/SourceSans3-Regular.ttf
        - asset: assets/fonts/SourceSans3-SemiBold.ttf
        - asset: assets/fonts/SourceSans3-SemiBoldItalic.ttf

